variables:
  # variables for docker service to build image during CI
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  
# service of dind to build image during CI
services:
  - docker:19.03.13-dind

test:
  stage: test
  image: golang:latest
  only:
    refs:
    - dev
    - master
  script:
  - source $ENV_VARS
  - go test ./...

build:
  stage: build
  image: docker:19.03.13
  only:
    refs:
    - dev
    - master
  script:
  - docker build -t ssl1321ois/ams_server:${CI_COMMIT_SHORT_SHA} .
  - docker login -u=${DOCKER_USER} -p=${DOCKER_PASSWORD}
  - docker push ssl1321ois/ams_server:${CI_COMMIT_SHORT_SHA}

deploy:
  stage: deploy
  image: nightlord851108/kustomize
  only:
    refs:
    - master
  script:
  - cd deployment/overlay
  - kustomize edit set image ssl1321ois/ams_server:${CI_COMMIT_BRANCH}.${CI_COMMIT_SHORT_SHA}
  - kustomize build . | kubectl apply --server=$${CLUSTER_URL} --token=$${CLUSTER_TOKEN} --insecure-skip-tls-verify=true --namespace=production -f -

stages:
- test
- build
- deploy
