// Code generated by MockGen. DO NOT EDIT.
// Source: ssl-gitlab.csie.ntut.edu.tw/ois/ois-project/ams/internal/repository (interfaces: TeamRepository)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "ssl-gitlab.csie.ntut.edu.tw/ois/ois-project/ams/internal/model"
)

// MockTeamRepository is a mock of TeamRepository interface.
type MockTeamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTeamRepositoryMockRecorder
}

// MockTeamRepositoryMockRecorder is the mock recorder for MockTeamRepository.
type MockTeamRepositoryMockRecorder struct {
	mock *MockTeamRepository
}

// NewMockTeamRepository creates a new mock instance.
func NewMockTeamRepository(ctrl *gomock.Controller) *MockTeamRepository {
	mock := &MockTeamRepository{ctrl: ctrl}
	mock.recorder = &MockTeamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamRepository) EXPECT() *MockTeamRepositoryMockRecorder {
	return m.recorder
}

// AddMembers mocks base method.
func (m *MockTeamRepository) AddMembers(arg0 []model.RoleRelation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMembers", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMembers indicates an expected call of AddMembers.
func (mr *MockTeamRepositoryMockRecorder) AddMembers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMembers", reflect.TypeOf((*MockTeamRepository)(nil).AddMembers), arg0)
}

// AddSubteams mocks base method.
func (m *MockTeamRepository) AddSubteams(arg0 []model.TeamRelation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSubteams", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSubteams indicates an expected call of AddSubteams.
func (mr *MockTeamRepositoryMockRecorder) AddSubteams(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSubteams", reflect.TypeOf((*MockTeamRepository)(nil).AddSubteams), arg0)
}

// AddTeam mocks base method.
func (m *MockTeamRepository) AddTeam(arg0 *model.Team) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTeam", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTeam indicates an expected call of AddTeam.
func (mr *MockTeamRepositoryMockRecorder) AddTeam(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTeam", reflect.TypeOf((*MockTeamRepository)(nil).AddTeam), arg0)
}

// GetBelongTeam mocks base method.
func (m *MockTeamRepository) GetBelongTeam(arg0 string) ([]model.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBelongTeam", arg0)
	ret0, _ := ret[0].([]model.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBelongTeam indicates an expected call of GetBelongTeam.
func (mr *MockTeamRepositoryMockRecorder) GetBelongTeam(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBelongTeam", reflect.TypeOf((*MockTeamRepository)(nil).GetBelongTeam), arg0)
}

// GetTeam mocks base method.
func (m *MockTeamRepository) GetTeam(arg0 string) (*model.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeam", arg0)
	ret0, _ := ret[0].(*model.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeam indicates an expected call of GetTeam.
func (mr *MockTeamRepositoryMockRecorder) GetTeam(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeam", reflect.TypeOf((*MockTeamRepository)(nil).GetTeam), arg0)
}

// RemoveMembers mocks base method.
func (m *MockTeamRepository) RemoveMembers(arg0 string, arg1 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMembers", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMembers indicates an expected call of RemoveMembers.
func (mr *MockTeamRepositoryMockRecorder) RemoveMembers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMembers", reflect.TypeOf((*MockTeamRepository)(nil).RemoveMembers), arg0, arg1)
}

// RemoveSubteams mocks base method.
func (m *MockTeamRepository) RemoveSubteams(arg0 string, arg1 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSubteams", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveSubteams indicates an expected call of RemoveSubteams.
func (mr *MockTeamRepositoryMockRecorder) RemoveSubteams(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSubteams", reflect.TypeOf((*MockTeamRepository)(nil).RemoveSubteams), arg0, arg1)
}

// UpdateUserRole mocks base method.
func (m *MockTeamRepository) UpdateUserRole(arg0, arg1 string, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserRole", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserRole indicates an expected call of UpdateUserRole.
func (mr *MockTeamRepositoryMockRecorder) UpdateUserRole(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserRole", reflect.TypeOf((*MockTeamRepository)(nil).UpdateUserRole), arg0, arg1, arg2)
}
